create extension if not exists pgcrypto;

create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sort_order integer not null default 0,
  hash_key text generated always as (encode(digest(lower(slug), 'sha256'), 'hex')) stored unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_sections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_slug text,
  eyebrow text not null,
  title text not null,
  intro text not null,
  sort_order integer not null default 0,
  hash_key text generated always as (encode(digest(lower(slug), 'sha256'), 'hex')) stored unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_groups (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.catalog_sections(id) on delete cascade,
  slug text not null,
  title text not null,
  sort_order integer not null default 0,
  hash_key text generated always as (encode(digest(lower(slug), 'sha256'), 'hex')) stored unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (section_id, slug)
);

create table if not exists public.catalog_products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_id bigint references public.product_categories(id) on delete set null,
  section_id bigint references public.catalog_sections(id) on delete set null,
  group_id bigint references public.catalog_groups(id) on delete set null,
  name text not null,
  title text not null,
  tagline text not null default '',
  description text not null default '',
  canonical_url text not null default '',
  hero_icon_svg text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  status text not null default 'published',
  metadata jsonb not null default '{}'::jsonb,
  hash_key text generated always as (encode(digest(lower(slug), 'sha256'), 'hex')) stored unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalog_product_features (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalog_products(id) on delete cascade,
  position integer not null,
  feature text not null,
  unique (product_id, position)
);

create table if not exists public.catalog_product_applications (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalog_products(id) on delete cascade,
  position integer not null,
  application text not null,
  unique (product_id, position)
);

create table if not exists public.catalog_product_specs (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalog_products(id) on delete cascade,
  position integer not null,
  label text not null,
  value text not null,
  unique (product_id, position)
);

create table if not exists public.catalog_product_relations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.catalog_products(id) on delete cascade,
  related_product_id bigint not null references public.catalog_products(id) on delete cascade,
  relation_type text not null default 'related',
  position integer not null default 0,
  unique (product_id, related_product_id, relation_type)
);

create table if not exists public.quote_sessions (
  id uuid primary key default gen_random_uuid(),
  session_hash text not null unique,
  status text not null default 'open',
  item_count integer not null default 0,
  total_quantity integer not null default 0,
  last_synced_at timestamptz not null default now(),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.quote_session_items (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.quote_sessions(id) on delete cascade,
  line_number integer not null,
  product_slug text,
  product_title text not null,
  product_specs text not null,
  image_url text not null,
  quantity integer not null default 1,
  item_hash text not null,
  created_at timestamptz not null default now(),
  unique (session_id, line_number),
  unique (session_id, item_hash)
);

create table if not exists public.quote_requests (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.quote_sessions(id) on delete set null,
  session_hash text not null,
  full_name text not null,
  email text not null,
  company text not null,
  notes text not null default '',
  item_count integer not null default 0,
  total_quantity integer not null default 0,
  status text not null default 'received',
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.quote_request_items (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.quote_requests(id) on delete cascade,
  line_number integer not null,
  product_slug text,
  product_title text not null,
  product_specs text not null,
  image_url text not null,
  quantity integer not null default 1,
  item_hash text not null,
  created_at timestamptz not null default now(),
  unique (request_id, line_number),
  unique (request_id, item_hash)
);

create table if not exists public.contact_inquiries (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  company text not null,
  inquiry_type text not null,
  message text not null default '',
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists catalog_products_section_idx on public.catalog_products (section_id, sort_order);
create index if not exists catalog_products_category_idx on public.catalog_products (category_id, sort_order);
create index if not exists catalog_groups_section_idx on public.catalog_groups (section_id, sort_order);
create index if not exists catalog_features_product_idx on public.catalog_product_features (product_id, position);
create index if not exists catalog_applications_product_idx on public.catalog_product_applications (product_id, position);
create index if not exists catalog_specs_product_idx on public.catalog_product_specs (product_id, position);
create index if not exists catalog_relations_product_idx on public.catalog_product_relations (product_id, position);
create index if not exists quote_sessions_status_idx on public.quote_sessions (status, updated_at desc);
create index if not exists quote_requests_created_at_idx on public.quote_requests (created_at desc);
create index if not exists contact_inquiries_created_at_idx on public.contact_inquiries (created_at desc);

alter table public.product_categories enable row level security;
alter table public.catalog_sections enable row level security;
alter table public.catalog_groups enable row level security;
alter table public.catalog_products enable row level security;
alter table public.catalog_product_features enable row level security;
alter table public.catalog_product_applications enable row level security;
alter table public.catalog_product_specs enable row level security;
alter table public.catalog_product_relations enable row level security;

drop policy if exists "Public read product categories" on public.product_categories;
create policy "Public read product categories" on public.product_categories for select using (true);

drop policy if exists "Public read catalog sections" on public.catalog_sections;
create policy "Public read catalog sections" on public.catalog_sections for select using (true);

drop policy if exists "Public read catalog groups" on public.catalog_groups;
create policy "Public read catalog groups" on public.catalog_groups for select using (true);

drop policy if exists "Public read catalog products" on public.catalog_products;
create policy "Public read catalog products" on public.catalog_products for select using (true);

drop policy if exists "Public read product features" on public.catalog_product_features;
create policy "Public read product features" on public.catalog_product_features for select using (true);

drop policy if exists "Public read product applications" on public.catalog_product_applications;
create policy "Public read product applications" on public.catalog_product_applications for select using (true);

drop policy if exists "Public read product specs" on public.catalog_product_specs;
create policy "Public read product specs" on public.catalog_product_specs for select using (true);

drop policy if exists "Public read product relations" on public.catalog_product_relations;
create policy "Public read product relations" on public.catalog_product_relations for select using (true);

create or replace function public.sync_quote_session(p_session_hash text, p_items jsonb default '[]'::jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_item_count integer;
  v_total_quantity integer;
begin
  v_item_count := coalesce(jsonb_array_length(coalesce(p_items, '[]'::jsonb)), 0);
  select coalesce(sum(greatest(1, coalesce((item->>'qty')::integer, 1))), 0)
    into v_total_quantity
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as item;

  insert into public.quote_sessions (session_hash, status, item_count, total_quantity, last_synced_at, updated_at)
  values (p_session_hash, 'open', v_item_count, v_total_quantity, now(), now())
  on conflict (session_hash) do update
    set status = 'open',
        item_count = excluded.item_count,
        total_quantity = excluded.total_quantity,
        last_synced_at = now(),
        updated_at = now()
  returning id into v_session_id;

  delete from public.quote_session_items where session_id = v_session_id;

  insert into public.quote_session_items (
    session_id,
    line_number,
    product_slug,
    product_title,
    product_specs,
    image_url,
    quantity,
    item_hash
  )
  select
    v_session_id,
    ordinality::integer,
    nullif(item->>'slug', ''),
    coalesce(item->>'title', ''),
    coalesce(item->>'specs', ''),
    coalesce(item->>'image', ''),
    greatest(1, coalesce((item->>'qty')::integer, 1)),
    encode(digest(p_session_hash || ':' || coalesce(item->>'title', '') || ':' || coalesce(item->>'specs', '') || ':' || ordinality::text, 'sha256'), 'hex')
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) with ordinality as item_rows(item, ordinality);

  return v_session_id;
end;
$$;

create or replace function public.submit_quote_request(p_session_hash text, p_contact jsonb, p_items jsonb default '[]'::jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_request_id uuid;
  v_item_count integer;
  v_total_quantity integer;
  v_full_name text;
  v_email text;
  v_company text;
  v_notes text;
begin
  v_session_id := public.sync_quote_session(p_session_hash, p_items);

  v_item_count := coalesce(jsonb_array_length(coalesce(p_items, '[]'::jsonb)), 0);
  select coalesce(sum(greatest(1, coalesce((item->>'qty')::integer, 1))), 0)
    into v_total_quantity
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as item;

  v_full_name := coalesce(p_contact->>'name', '');
  v_email := coalesce(p_contact->>'email', '');
  v_company := coalesce(p_contact->>'company', '');
  v_notes := coalesce(p_contact->>'notes', '');

  insert into public.quote_requests (
    session_id,
    session_hash,
    full_name,
    email,
    company,
    notes,
    item_count,
    total_quantity,
    status,
    created_at
  )
  values (
    v_session_id,
    p_session_hash,
    v_full_name,
    v_email,
    v_company,
    v_notes,
    v_item_count,
    v_total_quantity,
    'received',
    now()
  )
  returning id into v_request_id;

  insert into public.quote_request_items (
    request_id,
    line_number,
    product_slug,
    product_title,
    product_specs,
    image_url,
    quantity,
    item_hash
  )
  select
    v_request_id,
    ordinality::integer,
    nullif(item->>'slug', ''),
    coalesce(item->>'title', ''),
    coalesce(item->>'specs', ''),
    coalesce(item->>'image', ''),
    greatest(1, coalesce((item->>'qty')::integer, 1)),
    encode(digest(p_session_hash || ':request:' || coalesce(item->>'title', '') || ':' || coalesce(item->>'specs', '') || ':' || ordinality::text, 'sha256'), 'hex')
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) with ordinality as item_rows(item, ordinality);

  update public.quote_sessions
    set status = 'submitted',
        submitted_at = now(),
        updated_at = now()
  where id = v_session_id;

  return v_request_id;
end;
$$;

create or replace function public.submit_contact_inquiry(p_contact jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inquiry_id uuid;
begin
  insert into public.contact_inquiries (
    first_name,
    last_name,
    email,
    phone,
    company,
    inquiry_type,
    message,
    created_at
  )
  values (
    coalesce(p_contact->>'firstName', ''),
    coalesce(p_contact->>'lastName', ''),
    coalesce(p_contact->>'email', ''),
    coalesce(p_contact->>'phone', ''),
    coalesce(p_contact->>'company', ''),
    coalesce(p_contact->>'inquiryType', ''),
    coalesce(p_contact->>'message', ''),
    now()
  )
  returning id into v_inquiry_id;

  return v_inquiry_id;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.product_categories to anon, authenticated;
grant select on public.catalog_sections to anon, authenticated;
grant select on public.catalog_groups to anon, authenticated;
grant select on public.catalog_products to anon, authenticated;
grant select on public.catalog_product_features to anon, authenticated;
grant select on public.catalog_product_applications to anon, authenticated;
grant select on public.catalog_product_specs to anon, authenticated;
grant select on public.catalog_product_relations to anon, authenticated;

grant execute on function public.sync_quote_session(text, jsonb) to anon, authenticated;
grant execute on function public.submit_quote_request(text, jsonb, jsonb) to anon, authenticated;
grant execute on function public.submit_contact_inquiry(jsonb) to anon, authenticated;
